### ISSUE TITLE
Warnings print "PythonEmbedInR"

### ISSUE THREAD

**Issue by GabrielHoffman** [Sage-Bionetworks/synapser#201] opened 2018-11-06 19:38 UTC
## Operating system
OS X and CentOS 6.9 with R 3.5.1 and synapse 0.4.41

## Description of the problem
Minimal reproducible example: Running very simple code prints many warnings
```
library(GenomicRanges)
library(synapser)
gr = GRanges(rep(1, 2), IRanges(1:2, 1:2))
```
This results in output:
```
Found more than one class "DataFrame" in cache; using the first, from namespace 'S4Vectors'
Also defined by ‘PythonEmbedInR’
Found more than one class "DataFrame" in cache; using the first, from namespace 'S4Vectors'
Also defined by ‘PythonEmbedInR’
Found more than one class "DataFrame" in cache; using the first, from namespace 'S4Vectors'
Also defined by ‘PythonEmbedInR’
```
This only happens when `synapser` is loaded.

The real issue is when I use GRanges store large sets of genome intervals.  Then R prints this warning thousands of times and takes over my console.

I realized it was due to `synapses` based on:
https://sagebionetworks.jira.com/browse/SYNR-1318?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

## Output of `sessionInfo()`

```> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices datasets  utils
[8] methods   base

other attached packages:
[1] synapser_0.4.41      GenomicRanges_1.34.0 GenomeInfoDb_1.18.0
[4] IRanges_2.16.0       S4Vectors_0.20.0     BiocGenerics_0.28.0

loaded via a namespace (and not attached):
[1] zlibbioc_1.28.0        compiler_3.5.1         R6_2.3.0
[4] XVector_0.22.0         GenomeInfoDbData_1.2.0 RCurl_1.95-4.11
[7] pack_0.1-1             PythonEmbedInR_0.3.25  bitops_1.0-6
```

**Comment by kimyen** [comment] 2018-11-07 19:53
Hi @GabrielHoffman ,

Thank you for reporting the problem. Unfortunately, this is not a `synapser` issue. The issue you found was marked as blocked because the fix had to happen at `mygene` package. There is nothing we can do here. See my open Github issue for `mygene` here: https://github.com/biothings/mygene.R/issues/2

The issue you encounter can be reproduced without `synapser` similarly:
```
setClass("DataFrame")
library("GenomicRanges")
gr = GRanges(rep(1, 2), IRanges(1:2, 1:2))
```

Please open an issue with `GenomicRanges`.

**Closed by kimyen** 2018-11-07 19:53 UTC

**Comment by kimyen** [comment] 2018-11-19 19:06
Thanks @lawremi for the information. Do you know when the fix is released?

**Comment by lawremi** [comment] 2018-11-19 19:15
With the next release of R, which is not yet set. I am porting to the 3.5 branch now so probably sooner than May.

**Comment by kimyen** [comment] 2018-11-19 21:14
Thank you so much, @lawremi !
