### ISSUE TITLE
Not able to authenticate using all possible ways

### ISSUE THREAD

**Issue by guodudou** [Sage-Bionetworks/synapser#304] opened 2022-04-21 15:45 UTC
## Operating system
Windows 10 
R is installed in ~/laptop/OneDrive/Documents/R/R-4.1.3
.synapseConfig is saved under ~

## Description of the problem

I registered a synapse account, and installed "synapser" package in R . I created a token with full permission including view, and tried all the ways mentioned in https://r-docs.synapse.org/articles/manageSynapseCredentials.html#kimyen-ladia to authenticate using synLogin(), but failed with error message "Error in value[[3L]](cond) : 
  HTTPSConnectionPool(host='repo-prod.prod.sagebase.org', port=443): Max retries exceeded with url: /repo/v1/userProfile (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))"

### Expected behavior

Be able to authenticate

### Actual behavior

failed

## Output of `sessionInfo()`

> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] synapser_0.11.7

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3         knitr_1.38           magrittr_2.0.2       tidyselect_1.1.2     R6_2.5.1             rlang_1.0.2          fastmap_1.1.0       
 [8] fansi_1.0.3          dplyr_1.0.8          tools_4.1.3          xfun_0.30            utf8_1.2.2           cli_3.2.0            DBI_1.1.2           
[15] htmltools_0.5.2      ellipsis_0.3.2       yaml_2.3.5           assertthat_0.2.1     digest_0.6.29        tibble_3.1.6         lifecycle_1.0.1     
[22] crayon_1.5.1         zip_2.2.0            PythonEmbedInR_0.8.4 purrr_0.3.4          codetools_0.2-18     vctrs_0.3.8          glue_1.6.2          
[29] evaluate_0.15        rmarkdown_2.13       openxlsx_4.2.5       stringi_1.7.6        compiler_4.1.3       pillar_1.7.0         pack_0.1-1          
[36] generics_0.1.2       pkgconfig_2.0.3 

Thank you very much!
Wendy

**Comment by thomasyu888** [comment] 2023-03-04 00:50
Apologies for the large delays in response. @guodudou .  This error seems to be caused by the synapse backend being blocked.  Please see this to see if your institution can allow for these IP addresses. https://help.synapse.org/docs/Synapse-Infrastructure.2835382273.html

**Comment by thomasyu888** [comment] 2023-03-27 05:07
Going to close this for now - please re-open if you still encounter this issue.  Thanks!

**Closed by thomasyu888** 2023-03-27 05:07 UTC
